"""Parámetros de la dinámica de activación (SPEC §5) — nada de números mágicos sueltos."""

from pydantic import BaseModel, Field


class DynamicsConfig(BaseModel):
    boost: float = Field(2.0, description="Impulso de resonancia (× similitud). Recalibrado a 2.0 con la equiparación: al no fabricarse energía, el nivel absoluto baja y el impulso inicial debe compensar (ablación jul 2026)")
    struct_bonus: float = Field(1.5, description="Multiplicador si la arista también coincide")
    sim_threshold: float = Field(0.80, description="Similitud coseno mínima para match de nodo (vía semántica)")
    lexical_floor: float = Field(0.45, description="Coseno mínimo para aceptar un rescate LÉXICO (BM25): el nombre coincide en superficie ('guggen'⊂'museo guggenheim', cos≈0.73) pero por debajo de este suelo un token compartido no basta — evita falsos positivos. Debe ser < sim_threshold")
    lexical_k: int = Field(5, description="Candidatos léxicos (BM25) que se traen para que el coseno desambigüe")
    rounds: int = Field(2, description="Rondas síncronas amortiguadas de propagación")
    damping: float = Field(0.5, description="Fracción de activación repartida a vecinos por ronda")
    back_factor: float = Field(0.5, description="Atenuación contra el sentido de la arista")
    spread_back_factor: float | None = Field(None, description="Override de back_factor SOLO para la propagación al percibir (None = usa back_factor). Permite ablacionar 'solo a favor de la flecha' (0.0) sin romper la evocación, que necesita el backward para llegar de la categoría a sus miembros")
    spread_equalizes: bool = Field(True, description="Si True, la propagación es EQUIPARACIÓN por gradiente (difusión): el calor fluye solo del más caliente al más frío, proporcional a la diferencia, y el origen CEDE lo que fluye — se igualan, nunca se cruzan (lo percibido queda siempre por encima de lo primado). Un subgrafo en silencio no gana energía: el decay siempre acaba enfriándolo (imposibilidad estructural del 'motor perpetuo'). Contra la flecha el flujo va atenuado por back_factor (back_factor=0 → solo a favor de la flecha). False = histórico (suma sin restar → realimentación que satura; solo para ablaciones). Defecto True desde jul 2026: ablación (0.55→0.73) y corrida conjunta (0.75 vs 0.55, p<1e-4) en evaluation/")
    decay: float = Field(0.80, description="Decaimiento exponencial por turno: ~4-5 turnos activo y bajada suave (0.90 era glacial, 0.70 demasiado agresivo)")
    eta: float = Field(0.1, description="Tasa hebbiana: weight += eta · act(A) · act(B)")
    coact_threshold: float = Field(0.5, description="Activación mínima para refuerzo por co-activación")
    retrieval_threshold: float = Field(1.0, description="Activación mínima para entrar en el recall")
    recall_max_nodes: int = Field(8, description="Solo los K nodos más activos entran al recall: prioriza y CORTA (recencia gana, hubs fríos fuera), en vez de volcar todo el subgrafo")
    recall_max_episodes: int = Field(4, description="Episodios literales inyectados, de los nodos MÁS activos primero: corta el arrastre de distractores")
    recall_relevance_gain: float = Field(1.0, description="Gradación del orden del recall: score = gain·relevancia_evocada + base_strength. La relevancia (~0.01-0.18) y la importancia (~0.2-1.1) viven en escalas dispares; a 1.0 (defecto = comportamiento actual) la importancia domina y entierra miembros relevantes pero poco consolidados. Subirlo deja que la relevancia a la pregunta pese de verdad (el 'dragón' de la gradación, SPEC §5). Ablación en evaluation/grading.py")
    testing_effect: float = Field(0.02, description="Efecto testeo (ACT-R): recordar consolida — incremento de base_strength de cada nodo INYECTADO en un recall con contenido. Refuerza la escala lenta, nunca la activación: la fuerza no se propaga, así que no puede realimentarse (sin motor perpetuo). 0.0 = apagado")
    evoke_rounds: int = Field(3, description="Rondas de propagación al evocar (rebuscar): alcance para llegar a lo lejano/frío")
    evoke_damping: float = Field(0.7, description="Fracción transmitida por ronda en la evocación (menos amortiguada que el percibir)")
    context_window: int = Field(3, description="Turnos recientes cuyos conceptos siguen contando como pista de evocación (el hilo de la conversación, para preguntas elípticas)")
    surprise_min_expectation: float = Field(2.0, description="Activación total previa mínima para que haya expectativa: sobre una red fría nada sorprende")
    surprise_threshold: float = Field(0.12, description="Sorpresa (relativa al hilo) desde la que se avisa de una ligera desviación")
    surprise_threshold_high: float = Field(0.25, description="Sorpresa desde la que el aviso es de ruptura marcada del hilo")
    attention_budget: int = Field(1500, description="Tokens máximos de memoria inyectada por turno")
    episode_context_turns: int = Field(0, description="Turnos VECINOS inyectados alrededor de cada episodio recordado (±N, en orden cronológico): la respuesta de un diálogo vive a menudo en la implicatura del hilo adyacente ('¡5 años ya!' = el aniversario del turno anterior). 0 = solo el turno recordado (defecto: los hechos puntuales no lo necesitan, y con hechos confusables en turnos consecutivos —distractores— los vecinos contaminarían)")
    strength_decay: float = Field(0.95, description="Decaimiento lento de base_strength por ciclo de sueño (0.99 era glacial: ~70 ciclos para olvidar la mitad)")
    activation_cap: float = Field(5.0, description="Techo de activación por nodo (saturación)")
    activation_budget: float = Field(50.0, description="Activación total máxima (inhibición lateral)")
    activation_floor: float = Field(0.05, description="Bajo este valor, la activación se fija a 0")
    fanout_k: int = Field(10, description="Aristas más fuertes por nodo en la propagación")
    window_max_turns: int = Field(16, description="Turnos máximos de la ventana conversacional")
    window_keep_turns: int = Field(8, description="Turnos conservados al truncar en bloque")
    flashbulb_threshold: float = Field(0.9, description="Salience que dispara el imprint directo")
    consolidate_every: int = Field(20, description="Cadencia de sueño en replay (turnos); en vivo manda la inactividad")
    idle_sleep_seconds: float = Field(300, description="Segundos de conversación quieta tras los que la mente se duerme")
    merge_review_sim: float = Field(0.70, description="Similitud desde la que un par es candidato a fusión (decide el LLM)")
    merge_auto_sim: float = Field(0.92, description="Similitud desde la que la fusión no necesita LLM")
    coact_promote_count: int = Field(3, description="Co-activaciones sin arista que el sueño promueve a arista")
    coact_focus_k: int = Field(5, description="Solo los K nodos más activos del turno forman pares de co-activación: un turno de N conceptos no crea C(N,2) trazas (anti-hairball)")
    coact_assoc_min: float = Field(0.3, description="Asociación mínima count/√(eventos_a·eventos_b) para promover: un nodo caliente-en-todo (muchos eventos) no se cablea con todo — asociación, no frecuencia (≈ rechaza > ~11 vecinos)")
    strength_transfer: float = Field(0.1, description="Transferencia a largo plazo: strength += tasa · act · salience")
    consolidation_floor: float = Field(0.12, description="Suelo de NO-RETORNO: una vez base_strength lo cruza, el hecho es permanente — no decae por debajo ni se poda. Debe ser > fade_threshold")
    salience_deposit: float = Field(0.35, description="Depósito inmediato a base_strength por mención (= salience·este, vía imprint graduado): salience ≳ floor/este cruza el suelo al instante (emoción genera recuerdo); lo trivial no llega")
    fade_threshold: float = Field(0.05, description="base_strength bajo el cual un nodo inactivo se poda (lógicamente)")
    fade_grace_turns: int = Field(20, description="Turnos de gracia antes de que un nodo pueda podarse")
    episode_min_cluster: int = Field(3, description="Nodos mínimos de un clúster caliente para abstraer un episodio")
    consciousness_enabled: bool = Field(False, description="La voz (consciencia de SOLO LECTURA): tras cada turno, ChatSession verbaliza la coalición activa en un pensamiento con valencia y sorpresa, de forma asíncrona (el turno nunca la espera). Apagada = invarianza total con el comportamiento sin voz. Mind.consciousness() funciona siempre bajo demanda, con o sin este flag: el flag gobierna solo el disparo automático por turno")
    consciousness_every: int = Field(1, description="Cadencia de la voz en TURNOS (el tiempo es conversacional, no hay reloj): un pensamiento cada N turnos")
    consciousness_top_k: int = Field(6, description="Nodos de la coalición dominante (los más activos) que forman el material del pensamiento")
    consciousness_max_episodes: int = Field(2, description="Fragmentos literales de episodios testigo (del nodo más activo) que acompañan a la coalición: el material sale entero del grafo, la voz no puede inventar")
    consciousness_max_words: int = Field(40, description="Presupuesto de palabras del pensamiento: la voz es un RESUMEN objetivo del contenido activo en como máximo estas palabras, sin aspectos poéticos")
